config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get '/choose' => 'questions#choose'
  get '/reset' => 'questions#reset'

  resources :questions,  only: [:index, :new, :create]

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :question, presence: true

  def self.reset
    Question.find_each { |q| q.seen = false; q.save }
  end
end

app/models/shuffle_queue.rb
class ShuffleQueue

  def initialize
    @questions = Question.where(seen: false).uniq
  end

  def shuffle!
    @questions.shuffle!
  end

  def last
    question_id = @questions.pluck(:id).pop
    question = Question.find(question_id)
    question.update_attribute(:seen, true)
    question.question
  end

  def any?
    @questions.any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_url, notice: 'Thanks!'
    else
      flash.now.alert = 'Form incomplete - please ensure that you have filled out all fields.'
      render 'new'
    end
  end

  def choose
    questions = ShuffleQueue.new

    if questions.any?
      @quest = questions.last
    else
      redirect_to root_url, alert: 'No questions or topics left!'
    end
  end

  def reset
    Question.reset
    redirect_to root_url
  end

  private

  def question_params
    params.require(:question).permit(
    :question
    ).merge(seen: false)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SheCodesQuestions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
	  <a class="navbar-brand" href="/">Home</a>
        </div>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div data-alert class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div data-alert class="alert alert-danger">
       <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/choose.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Randomly Selected:</h1>
    <div class="well well-lg">
      <p class="question"><%= @quest %></p>
    </div>
    <%= link_to "Choose another", choose_path, class: "btn btn-lg btn-success" %>
  </div>
</div>
<%= @size %>

app/views/questions/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>She Codes - The Salon</h1>
    <p class="lead">Welcome! Please submit question/topic ideas! Submissions are anonymous!</p>
    <%= link_to "Enter a question or topic", new_question_path, class: "btn btn-lg btn-success" %>
    <%= link_to "Choose a topic or question at random", choose_path, class: "btn btn-lg btn-info" %>
  </div>
</div>

app/views/questions/new.html.erb
<h1>Enter a Question or Topic!</h1>
<%= form_for @question, html: {role: "form"} do |f| %>
  <div class="row">
    <%= f.text_field :question, class: "form-control input-lg" %>
  </div>
  <div class="row">
    <%= f.submit 'Submit!' %>
  </div>
<% end %>